### PR TITLE
fix: M962. couldnt reproduce, but audited code and referring to repor…

### PR DESCRIPTION
**Pull request by mmnoo**
…ted stack trace to make it not crash

Ticket: https://trello.com/c/qPebUCwf/962-lit-cr-validation-typeerror

This is another fixing an error that I cant reproduce. Just adding some more diligent logic. 

No testing.

### CODE REVIEW

**Comment by mmnoo** [comment]
[LIT/CR validation TypeError](https://trello.com/c/qPebUCwf/962-lit-cr-validation-typeerror)

**Review by julia-rom — APPROVED** [review]
would `.validations.data` include` obs_benthic_pits`? just checking if that's what data represents here. Looking at the type error in the ticket

**Comment by mmnoo** [comment]
> would `.validations.data` include` obs_benthic_pits`? just checking if that's what data represents here. Looking at the type error in the ticket

Yup. A few lines lower is what throws the error
`  modifiedCollectRecordWithResetObservationValidations.validations.results.data[
            observationTableName
          ]`
          
          `observationTableName` = obs_benthic_pits where the error was thrown

**Comment by julia-rom** [comment]
> > would `.validations.data` include` obs_benthic_pits`? just checking if that's what data represents here. Looking at the type error in the ticket
> 
> Yup. A few lines lower is what throws the error ` modifiedCollectRecordWithResetObservationValidations.validations.results.data[ observationTableName ]`
> 
> `observationTableName` = `obs_benthic_pits` where the error was thrown

ahh got it! ok good to approve in that case

**Pull request merged**
