### PR TITLE
[776] update pins on project sites page to use clusters instead of markers

### PR DESCRIPTION
**Pull request by julia-rom**
[trello card](https://trello.com/c/GaCk2wVc/776-not-all-pins-are-shown-on-the-sites-page-map)

## Summary by CodeRabbit

- **New Features**
    - Enhanced map functionality with cluster sources, layers, and event listeners.
    - Improved map marker updates and initialization process.
- **Refactor**
    - Streamlined imports and updated props for better performance and maintainability.
    - Simplified and consolidated map-related functions for improved clarity.

### CODE REVIEW

**Comment by julia-rom** [comment]
Screenshot 2024-07-05 at 10 35 32 AM

**Review by alanjleonard — CHANGES_REQUESTED** [review]
Works good. 

Just need to update styles of pins.

Use this red for pins #A53434
 
**Multi site marker** 
- red with white border 
- Show number of site
- bigger than single site 

**Single site marker** 
- red with white border
- no number
- Smaller

**Selected site**
- pin icon
- popover (already implemented)

**Comment by julia-rom** [comment]
Screenshot 2024-07-05 at 2 31 53 PM

**Review by alanjleonard — APPROVED** [review]

**Review by gwan93 — APPROVED** [review]
Looks good and works well!

**Pull request merged**
