### PR TITLE
Minor UI tweaks

### PR DESCRIPTION
**Pull request by alanjleonard**
Multiple tickets. See commit messages.

### CODE REVIEW

**Comment by alanjleonard** [comment]
[Project already exists error alignment.](https://trello.com/c/fH4GjZzg/871-project-already-exists-error-alignment)

**Comment by alanjleonard** [comment]
[Inconsistent hover state on add sample unit and export to XLSX dropdowns.](https://trello.com/c/MJLS6BGY/984-inconsistent-hover-state-on-add-sample-unit-and-export-to-xlsx-dropdowns)

**Review by mmnoo — APPROVED** [review]

**Comment by alanjleonard** [comment]
[Alignment of the checkbox in the observers field.](https://trello.com/c/qysIJlfW/869-alignment-of-the-checkbox-in-the-observers-field)

**Comment by alanjleonard** [comment]
[Styles for ignore warning checkbox in observation table.](https://trello.com/c/GmGwEhdF/967-styles-for-ignore-warning-checkbox-in-observation-table)

**Pull request merged**
