### PR TITLE
Melissa/842 3

### PR DESCRIPTION
**Pull request by mmnoo**
A speculative improvements for a bug that I couldnt reproduce (see ticket comments https://trello.com/c/k4O2MjrT/842-audit-cryptic-toast-error-messages)
speeding up pre push test hook

### CODE REVIEW

**Comment by mmnoo** [comment]
[audit cryptic toast error messages](https://trello.com/c/k4O2MjrT/842-audit-cryptic-toast-error-messages)

**Review by julia-rom — COMMENTED** [review]
had a look at the ticket and a bit confused - is the issue here that the error is unclear? my assumption would be that it is an api error and to try refreshing. How will this make it clearer to the user?

**Comment by mmnoo** [comment]
> had a look at the ticket and a bit confused - is the issue here that the error is unclear? my assumption would be that it is an api error and to try refreshing. How will this make it clearer to the user?

good question. This bug came up as part of the audit work, but I dont have enough details on the bug itself, but we discussed verbally that I reverse engineer what might possibly be triggering it and fix it, even if speculatively. So I added some try/catch and .?

**Comment by julia-rom** [comment]
ah got it - as long as that's flagged in the ticket i'm ok to approve!

**Pull request merged**
